name: brave
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - torch==2.7.1
    - torchvision==0.22.1
    - timm==1.0.19
    - peft==0.17.0
    - loralib==0.1.2
    - h5py==3.14.0
    - wandb==0.21.0
    - numpy==1.26.4
    - Pillow==11.3.0
    - huggingface-hub==0.34.3
    - xformers==0.0.31.post1
    - submitit==1.5.3
    - transformers==4.54.1
    - torchmetrics==0.10.3
