name: brave
channels:
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.9
  - pytorch::pytorch=2.0.0
  - pytorch::pytorch-cuda=11.7.0
  - pytorch::torchvision=0.15.0
  - pip:
    - timm
    - peft
    - loralib
    - h5py
    - wandb
    - numpy
    - Pillow
